# Generated by Django 2.0.5 on 2020-01-07 01:07

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('blog_app', '0003_auto_20200107_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tages',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
