# Generated by Django 2.0.5 on 2020-01-07 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_post_tages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tages',
            new_name='tags',
        ),
    ]
